import {
  StudentProfile,
  TeacherProfile,
  User,
  Subject,
  Chapter,
  Lesson,
  Package,
  Transaction,
  LiveClass,
  Quiz,
  WatchProgress,
  NotificationItem,
  QuizAttempt,
} from '../types';

export const DEMO_STUDENT: StudentProfile = {
  id: 'stu-alex-001',
  name: 'Alex',
  email: 'alex.c8@edexora.edu',
  role: 'student',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  phone: '+91 98765 43210',
  status: 'active',
  classLevel: 8,
  curriculum: 'CBSE',
  parentName: 'Robert Johnson',
  parentPhone: '+91 98765 00000',
  totalClassesUnlocked: 10,
  completedClassesCount: 6,
  remainingClassesCount: 4,
  currentPackageId: 'pkg-10-class',
  enrolledSubjectIds: ['sub-math-8', 'sub-sci-8', 'sub-eng-8', 'sub-soc-8'],
};

export const DEMO_TEACHERS: TeacherProfile[] = [
  {
    id: 'tch-sarah-01',
    name: 'Dr. Sarah Thomas',
    email: 'sarah.thomas@edexora.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+91 94471 23456',
    status: 'active',
    qualification: 'Ph.D. in Mathematics, B.Ed',
    experienceYears: 12,
    assignedSubjectIds: ['sub-math-8', 'sub-math-9', 'sub-math-10'],
    assignedClassLevels: [8, 9, 10],
    bio: 'Senior Mathematics Educator specializing in CBSE and Kerala State Higher Secondary algebra and geometry.',
  },
  {
    id: 'tch-menon-02',
    name: 'Prof. K.V. Menon',
    email: 'kv.menon@edexora.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98470 11223',
    status: 'active',
    qualification: 'M.Sc Physics, Gold Medalist',
    experienceYears: 15,
    assignedSubjectIds: ['sub-sci-8', 'sub-phy-9', 'sub-phy-10'],
    assignedClassLevels: [7, 8, 9, 10],
    bio: 'Passionate Physics educator making complex scientific phenomena intuitive and fun for school students.',
  },
  {
    id: 'tch-anjali-03',
    name: 'Ms. Anjali Nair',
    email: 'anjali.nair@edexora.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    phone: '+91 97455 33445',
    status: 'active',
    qualification: 'M.A. Malayalam Literature, B.Ed',
    experienceYears: 8,
    assignedSubjectIds: ['sub-mal-8', 'sub-mal-7'],
    assignedClassLevels: [5, 6, 7, 8],
    bio: 'Kerala State curriculum specialist in Malayalam language, grammar, and classical literature.',
  },
  {
    id: 'tch-rajesh-04',
    name: 'Mr. Rajesh Kumar',
    email: 'rajesh.k@edexora.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99951 88776',
    status: 'active',
    qualification: 'M.A. English & Communication',
    experienceYears: 10,
    assignedSubjectIds: ['sub-eng-8', 'sub-eng-9'],
    assignedClassLevels: [6, 7, 8, 9, 10],
    bio: 'Interactive English grammar, composition, and literature mentor for primary and secondary classes.',
  },
];

export const DEMO_ADMIN: User = {
  id: 'admin-001',
  name: 'EDEXORA Administrator',
  email: 'admin@edexora.com',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  phone: '+91 484 2300 900',
  status: 'active',
};

export const DEMO_ALL_STUDENTS: StudentProfile[] = [
  DEMO_STUDENT,
  {
    id: 'stu-002',
    name: 'Devika S. Menon',
    email: 'devika.m@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98460 11111',
    status: 'active',
    classLevel: 8,
    curriculum: 'Kerala State',
    parentName: 'Suresh Menon',
    parentPhone: '+91 98460 00000',
    totalClassesUnlocked: 20,
    completedClassesCount: 14,
    remainingClassesCount: 6,
    currentPackageId: 'pkg-25-class',
    enrolledSubjectIds: ['sub-math-8', 'sub-mal-8'],
  },
  {
    id: 'stu-003',
    name: 'Rohan Sharma',
    email: 'rohan.s@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 12345',
    status: 'active',
    classLevel: 10,
    curriculum: 'CBSE',
    parentName: 'Vikram Sharma',
    parentPhone: '+91 98765 99999',
    totalClassesUnlocked: 50,
    completedClassesCount: 42,
    remainingClassesCount: 8,
    currentPackageId: 'pkg-50-class',
    enrolledSubjectIds: ['sub-math-10', 'sub-sci-10'],
  },
  {
    id: 'stu-004',
    name: 'Meera Pillai',
    email: 'meera.p@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+91 97444 88888',
    status: 'active',
    classLevel: 5,
    curriculum: 'Kerala State',
    parentName: 'Gopakumar Pillai',
    parentPhone: '+91 97444 00000',
    totalClassesUnlocked: 10,
    completedClassesCount: 8,
    remainingClassesCount: 2,
    currentPackageId: 'pkg-10-class',
    enrolledSubjectIds: ['sub-math-5'],
  },
  {
    id: 'stu-005',
    name: 'Arjun Varma',
    email: 'arjun.v@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99955 44332',
    status: 'active',
    classLevel: 3,
    curriculum: 'CBSE',
    parentName: 'Priya Varma',
    parentPhone: '+91 99955 00000',
    totalClassesUnlocked: 10,
    completedClassesCount: 3,
    remainingClassesCount: 7,
    currentPackageId: 'pkg-10-class',
    enrolledSubjectIds: ['sub-math-3'],
  },
  {
    id: 'stu-006',
    name: 'Fatima Zohra',
    email: 'fatima.z@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 96333 22110',
    status: 'active',
    classLevel: 9,
    curriculum: 'CBSE',
    parentName: 'Tariq Zohra',
    parentPhone: '+91 96333 00000',
    totalClassesUnlocked: 25,
    completedClassesCount: 25,
    remainingClassesCount: 0,
    currentPackageId: 'pkg-25-class',
    enrolledSubjectIds: ['sub-math-9'],
  },
  {
    id: 'stu-007',
    name: 'Kevin Joseph',
    email: 'kevin.j@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98950 77665',
    status: 'inactive',
    classLevel: 7,
    curriculum: 'Kerala State',
    parentName: 'Joseph Mathew',
    parentPhone: '+91 98950 00000',
    totalClassesUnlocked: 0,
    completedClassesCount: 0,
    remainingClassesCount: 0,
    enrolledSubjectIds: [],
  },
  {
    id: 'stu-008',
    name: 'Sneha Krishnan',
    email: 'sneha.k@gmail.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+91 94000 55443',
    status: 'active',
    classLevel: 8,
    curriculum: 'CBSE',
    parentName: 'Unnikrishnan P.',
    parentPhone: '+91 94000 00000',
    totalClassesUnlocked: 10,
    completedClassesCount: 9,
    remainingClassesCount: 1,
    currentPackageId: 'pkg-10-class',
    enrolledSubjectIds: ['sub-math-8', 'sub-sci-8'],
  },
];

export const DEMO_PACKAGES: Package[] = [
  {
    id: 'pkg-10-class',
    name: 'Starter Learning Pack',
    classCount: 10,
    price: 500,
    validityDays: 30,
    description: 'Unlocks 10 complete video lessons & live session seats with study notes.',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'pkg-25-class',
    name: 'Pro Academic Bundle',
    classCount: 25,
    price: 1150,
    validityDays: 60,
    description: 'Unlocks 25 lessons across all subjects + priority live Q&A access.',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'pkg-50-class',
    name: 'Master Term Pass',
    classCount: 50,
    price: 2200,
    validityDays: 120,
    description: 'Comprehensive term package unlocking 50 lessons, practice quizzes & personal mentor feedback.',
    isPopular: false,
    isActive: true,
  },
];

export const DEMO_SUBJECTS: Subject[] = [
  {
    id: 'sub-math-8',
    name: 'Mathematics',
    code: 'MATH-C8',
    classLevel: 8,
    curriculum: 'CBSE',
    iconName: 'Calculator',
    color: '#FFD200',
    totalLessons: 12,
    description: 'Master Rational Numbers, Linear Equations, Quadratic Equations, and Geometry for Class 8.',
  },
  {
    id: 'sub-sci-8',
    name: 'Science & Physics',
    code: 'SCI-C8',
    classLevel: 8,
    curriculum: 'CBSE',
    iconName: 'Atom',
    color: '#3B82F6',
    totalLessons: 10,
    description: 'Explore Force, Pressure, Sound, Chemical Effects of Electric Current, and Light.',
  },
  {
    id: 'sub-eng-8',
    name: 'English Grammar & Lit.',
    code: 'ENG-C8',
    classLevel: 8,
    curriculum: 'CBSE',
    iconName: 'BookOpen',
    color: '#10B981',
    totalLessons: 8,
    description: 'Hone reading comprehension, active voice, essay composition, and literary prose.',
  },
  {
    id: 'sub-soc-8',
    name: 'Social Science',
    code: 'SOC-C8',
    classLevel: 8,
    curriculum: 'CBSE',
    iconName: 'Globe',
    color: '#F59E0B',
    totalLessons: 8,
    description: 'Indian Constitution, Judiciary, Colonialism, and Resource & Agriculture studies.',
  },
  {
    id: 'sub-mal-8',
    name: 'Malayalam (കേരള പാഠാവലി)',
    code: 'MAL-K8',
    classLevel: 8,
    curriculum: 'Kerala State',
    iconName: 'Languages',
    color: '#EC4899',
    totalLessons: 10,
    description: 'Kerala State Board Malayalam grammar, poetry analysis, and prose composition.',
  },
];

export const DEMO_CHAPTERS: Chapter[] = [
  {
    id: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Chapter 3: Quadratic & Linear Equations',
    order: 3,
    totalLessons: 6,
  },
  {
    id: 'chap-math-4',
    subjectId: 'sub-math-8',
    title: 'Chapter 4: Geometry & Polygons',
    order: 4,
    totalLessons: 6,
  },
  {
    id: 'chap-sci-1',
    subjectId: 'sub-sci-8',
    title: 'Chapter 1: Force and Pressure',
    order: 1,
    totalLessons: 5,
  },
];

export const DEMO_LESSONS: Lesson[] = [
  {
    id: 'les-m3-01',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Introduction to Linear Equations with One Variable',
    description: 'Understand the concept of algebraic expressions, LHS vs RHS balance, and transposition method step-by-step.',
    durationMinutes: 45,
    durationFormatted: '45 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 1,
    studyMaterialsCount: 3,
    quizId: 'quiz-math-c3-01',
    isLockedDefault: false,
  },
  {
    id: 'les-m3-02',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Solving Equations Having Variables on Both Sides',
    description: 'Learn how to simplify multi-term equations by grouping like terms and clearing fractions.',
    durationMinutes: 40,
    durationFormatted: '40 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 2,
    studyMaterialsCount: 2,
    quizId: 'quiz-math-c3-02',
    isLockedDefault: false,
  },
  {
    id: 'les-m3-03',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Word Problems: Age, Perimeter & Money Applications',
    description: 'Translating real-world word scenarios into algebraic equations and solving for unknown variables.',
    durationMinutes: 50,
    durationFormatted: '50 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 3,
    studyMaterialsCount: 4,
    quizId: 'quiz-math-c3-03',
    isLockedDefault: false,
  },
  {
    id: 'les-m3-04',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Reducing Equations to Simpler Form & Cross Multiplication',
    description: 'Master cross-multiplication technique for linear algebraic ratios and fractional equations.',
    durationMinutes: 38,
    durationFormatted: '38 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 4,
    studyMaterialsCount: 2,
    isLockedDefault: false,
  },
  {
    id: 'les-m3-05',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Quadratic Equations: Standard Form & Factoring',
    description: 'Introduction to degree 2 polynomial equations ax² + bx + c = 0 and splitting the middle term.',
    durationMinutes: 52,
    durationFormatted: '52 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 5,
    studyMaterialsCount: 3,
    isLockedDefault: false,
  },
  {
    id: 'les-m3-06',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Quadratic Formula & Nature of Roots (Discriminant Δ)',
    description: 'Derivation of x = (-b ± √(b²-4ac)) / 2a and calculating discriminant to test real vs equal roots.',
    durationMinutes: 45,
    durationFormatted: '45 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 6,
    studyMaterialsCount: 5,
    quizId: 'quiz-math-c3-06',
    isLockedDefault: false, // This is the 6th lesson completed
  },
  {
    id: 'les-m3-07',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Advanced Applications of Quadratic Equations',
    description: 'Speed-distance-time and river upstream-downstream word problems using quadratic models.',
    durationMinutes: 48,
    durationFormatted: '48 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 7,
    studyMaterialsCount: 3,
    isLockedDefault: false, // 7th lesson (1 of remaining 4)
  },
  {
    id: 'les-m3-08',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Completing the Square Method & Graphical Parabola',
    description: 'Step-by-step technique to transform quadratic expressions into perfect square form.',
    durationMinutes: 55,
    durationFormatted: '55 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 8,
    studyMaterialsCount: 2,
    isLockedDefault: false, // 8th lesson
  },
  {
    id: 'les-m3-09',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Simultaneous Equations & Substitution Method',
    description: 'Solving 2 linear equations in 2 variables using substitution and elimination tactics.',
    durationMinutes: 42,
    durationFormatted: '42 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutback2012.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 9,
    studyMaterialsCount: 4,
    isLockedDefault: false, // 9th lesson
  },
  {
    id: 'les-m3-10',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Chapter 3 Final Revision & Board Exam Model Questions',
    description: 'Comprehensive problem solving set covering past 5 years CBSE question patterns.',
    durationMinutes: 60,
    durationFormatted: '60 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 10,
    studyMaterialsCount: 5,
    isLockedDefault: false, // 10th lesson - end of package 1
  },
  {
    id: 'les-m3-11',
    chapterId: 'chap-math-3',
    subjectId: 'sub-math-8',
    title: 'Bonus Mastery Class: Olympiad & NTSE Advanced Algebra',
    description: 'High order thinking skills (HOTS) questions for competitive exam preparation.',
    durationMinutes: 65,
    durationFormatted: '65 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    order: 11,
    studyMaterialsCount: 6,
    isLockedDefault: true, // Requires Package 2 unlock!
  },
];

export const DEMO_WATCH_PROGRESS: WatchProgress[] = [
  {
    lessonId: 'les-m3-06',
    studentId: 'stu-alex-001',
    currentTimeSeconds: 1122, // 18 mins 42 seconds
    durationSeconds: 2700,
    percentage: 42,
    completed: false,
    lastWatchedAt: '2026-09-22T14:20:00Z',
  },
  {
    lessonId: 'les-m3-01',
    studentId: 'stu-alex-001',
    currentTimeSeconds: 2700,
    durationSeconds: 2700,
    percentage: 100,
    completed: true,
    lastWatchedAt: '2026-09-18T10:00:00Z',
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-10982',
    studentId: 'stu-alex-001',
    studentName: 'Alex',
    packageId: 'pkg-10-class',
    packageName: 'Starter Learning Pack (10 Classes)',
    amount: 500,
    classesUnlocked: 10,
    date: '2026-09-01 11:30 AM',
    paymentMethod: 'UPI',
    status: 'Successful',
    receiptNumber: 'EDX-2026-88912',
  },
  {
    id: 'txn-10940',
    studentId: 'stu-002',
    studentName: 'Devika S. Menon',
    packageId: 'pkg-25-class',
    packageName: 'Pro Academic Bundle (25 Classes)',
    amount: 1150,
    classesUnlocked: 25,
    date: '2026-09-05 02:15 PM',
    paymentMethod: 'Card',
    status: 'Successful',
    receiptNumber: 'EDX-2026-88901',
  },
  {
    id: 'txn-10901',
    studentId: 'stu-003',
    studentName: 'Rohan Sharma',
    packageId: 'pkg-50-class',
    packageName: 'Master Term Pass (50 Classes)',
    amount: 2200,
    classesUnlocked: 50,
    date: '2026-09-10 09:45 AM',
    paymentMethod: 'Netbanking',
    status: 'Successful',
    receiptNumber: 'EDX-2026-88760',
  },
  {
    id: 'txn-10888',
    studentId: 'stu-006',
    studentName: 'Fatima Zohra',
    packageId: 'pkg-10-class',
    packageName: 'Starter Learning Pack (10 Classes)',
    amount: 500,
    classesUnlocked: 10,
    date: '2026-09-15 04:20 PM',
    paymentMethod: 'UPI',
    status: 'Successful',
    receiptNumber: 'EDX-2026-88654',
  },
];

export const DEMO_LIVE_CLASSES: LiveClass[] = [
  {
    id: 'live-math-01',
    subjectId: 'sub-math-8',
    subjectName: 'Mathematics',
    chapterTitle: 'Chapter 4: Geometry & Polygons',
    topic: 'Live Problem Solving: Interior Angles & Diagonals of Polygons',
    teacherId: 'tch-sarah-01',
    teacherName: 'Dr. Sarah Thomas',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    classLevel: 8,
    curriculum: 'CBSE',
    startTime: 'Today, 7:00 PM – 8:00 PM',
    durationFormatted: '60 min',
    status: 'LIVE NOW',
    meetingLink: 'https://edexora.com/live/math-c8-live-01',
    attendeesCount: 42,
  },
  {
    id: 'live-sci-02',
    subjectId: 'sub-sci-8',
    subjectName: 'Science & Physics',
    chapterTitle: 'Chapter 1: Force & Atmospheric Pressure',
    topic: 'Interactive Physics Experiments & Barometer Calculations',
    teacherId: 'tch-menon-02',
    teacherName: 'Prof. K.V. Menon',
    teacherAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    classLevel: 8,
    curriculum: 'CBSE',
    startTime: 'Tomorrow, 6:30 PM – 7:30 PM',
    durationFormatted: '60 min',
    status: 'UPCOMING',
    meetingLink: 'https://edexora.com/live/sci-c8-live-02',
    attendeesCount: 38,
  },
  {
    id: 'live-mal-03',
    subjectId: 'sub-mal-8',
    subjectName: 'Malayalam',
    chapterTitle: 'കേരള സംസ്കാരം & കവിതാരചന',
    topic: 'പദ്യപാഠങ്ങൾ വ്യാകരണ വിശകലനം',
    teacherId: 'tch-anjali-03',
    teacherName: 'Ms. Anjali Nair',
    teacherAvatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    classLevel: 8,
    curriculum: 'Kerala State',
    startTime: '24 Sep, 5:00 PM – 6:00 PM',
    durationFormatted: '60 min',
    status: 'UPCOMING',
    attendeesCount: 29,
  },
];

export const DEMO_QUIZZES: Quiz[] = [
  {
    id: 'quiz-math-c3-06',
    lessonId: 'les-m3-06',
    subjectId: 'sub-math-8',
    title: 'Class 8 Mathematics: Linear & Quadratic Equations Test',
    durationMinutes: 15,
    totalMarks: 10,
    passingMarks: 6,
    questions: [
      {
        id: 'q1',
        text: 'What is the root of the equation 3x + 5 = 20?',
        options: ['x = 3', 'x = 5', 'x = 15', 'x = 4'],
        correctOptionIndex: 1,
        explanation: '3x = 20 - 5 => 3x = 15 => x = 5.',
      },
      {
        id: 'q2',
        text: 'The standard general form of a Quadratic Equation is:',
        options: ['ax + b = 0', 'ax² + bx + c = 0', 'ax³ + bx² + c = 0', 'a/x + b = 0'],
        correctOptionIndex: 1,
        explanation: 'A quadratic equation has degree 2: ax² + bx + c = 0 where a ≠ 0.',
      },
      {
        id: 'q3',
        text: 'If the Discriminant Δ = b² - 4ac > 0, the roots of the quadratic equation are:',
        options: ['Real and distinct', 'Real and equal', 'No real roots (imaginary)', 'Undefined'],
        correctOptionIndex: 0,
        explanation: 'When Δ > 0, the quadratic formula yields two distinct real values.',
      },
      {
        id: 'q4',
        text: 'Solve for x: (x / 2) + (x / 3) = 10',
        options: ['x = 6', 'x = 10', 'x = 12', 'x = 15'],
        correctOptionIndex: 2,
        explanation: 'LCM of 2 and 3 is 6. (3x + 2x)/6 = 10 => 5x/6 = 10 => 5x = 60 => x = 12.',
      },
      {
        id: 'q5',
        text: 'A rectangular field length is twice its breadth. If perimeter is 60m, find length:',
        options: ['10 m', '20 m', '30 m', '15 m'],
        correctOptionIndex: 1,
        explanation: 'Let breadth = b. Length = 2b. 2(2b + b) = 60 => 6b = 60 => b = 10m. Length = 20m.',
      },
    ],
  },
];

export const DEMO_QUIZ_ATTEMPTS: QuizAttempt[] = [
  {
    id: 'qa-001',
    quizId: 'quiz-math-c3-06',
    studentId: 'stu-alex-001',
    quizTitle: 'Class 8 Mathematics: Linear & Quadratic Equations Test',
    score: 8,
    totalMarks: 10,
    percentage: 80,
    timeSpentSeconds: 380,
    date: '2026-09-20 04:30 PM',
    passed: true,
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '🔴 LIVE Class Starting Now!',
    message: 'Dr. Sarah Thomas is live with Class 8 Mathematics: Interior Angles & Polygons.',
    category: 'Live',
    timestamp: '10 min ago',
    read: false,
  },
  {
    id: 'notif-2',
    title: '💳 Payment & 10 Classes Unlocked',
    message: 'Your payment of ₹500 was successful. 10 Classes unlocked in your account.',
    category: 'Payment',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-3',
    title: '🏆 Quiz Result Available',
    message: 'You scored 80% (8/10) in Class 8 Mathematics Test.',
    category: 'Quiz',
    timestamp: '1 day ago',
    read: true,
  },
  {
    id: 'notif-4',
    title: '📚 New Lesson Published',
    message: 'Chapter 3 Lesson 6: Quadratic Formula & Nature of Roots is now available.',
    category: 'Class',
    timestamp: '2 days ago',
    read: true,
  },
];
